break_into_partial_movies: false
camera_resolutions:
  4k: 3840x2160
  default_resolution: high
  high: 1920x1080
  low: 854x480
  medium: 1280x720
directories:
  mirror_module_path: false
  output: E:\manim\manim\media
  raster_images: E:\manim\manim\images
  sounds: E:\manim\manim\sound
  temporary_storage: E:\manim\manim\temp
  vector_images: E:\manim\manim\vimages
fps: 60
full_screen: false
style:
  background_color: '#333333'
  font: Consolas
  tex_template: default
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
